[package]
name = "nest_ui_api_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "1.3.56"
poem-openapi = { version = "2.0.27", features = ["swagger-ui"] }
tokio = { version = "1.29.1", features = ["macros", "rt", "rt-multi-thread"] }